# syntax=docker/dockerfile:1.7

FROM eclipse-temurin:21-jdk-jammy AS build
WORKDIR /app

# Install git so we can clone the shared-lib repository
RUN apt-get update && apt-get install -y git

# Clone shared-lib since it doesn't exist in the standalone service-auth repository
RUN git clone https://github.com/advprog-2026-A15-project/yomu-shared-lib.git ./shared-lib

# Copy the contents of the service-auth repository into /app/service-auth
COPY . ./service-auth

ARG CLEAN_GRADLE_CACHE=0

# Build shared-lib
RUN --mount=type=cache,target=/root/.gradle,sharing=locked if [ "$CLEAN_GRADLE_CACHE" = "1" ]; then rm -rf /root/.gradle/caches /root/.gradle/wrapper/dists; fi && \
    cd ./shared-lib && \
    sed -i 's/\r$//' ./gradlew && \
    chmod +x ./gradlew && \
    ./gradlew publishToMavenLocal --no-daemon

# Build service
RUN --mount=type=cache,target=/root/.gradle,sharing=locked cd ./service-auth && \
    sed -i 's/\r$//' ./gradlew && \
    chmod +x ./gradlew && \
    ./gradlew bootJar --no-daemon

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/service-auth/build/libs/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
